name: final-group08
channels:
  - conda-forge
  - nodefaults
  - defaults
dependencies:
  - python=3.12
  - ipykernel
  - ipywidgets
  - jupyter-ai
  - jupyterlab
  - jupytext
  - matplotlib
  - missingno
  - mlcroissant
  - nbconvert
  - numpy
  - pandas
  - pandera
  - pandoc
  - playwright
  - pyjanitor
  - pytest
  - quarto-cli
  - scikit-learn
  - scipy
  - seaborn
  - texlive-core
  - pip
  - pip:
      - -e .
prefix: /home/jovyan/.local/share/envs/final-group08
