name: final-group08
channels:
  - conda-forge
  - nodefaults
  - defaults
dependencies:
  - python=3.12
  - ipykernel
  - jupyterlab
  - matplotlib
  - mlcroissant
  - numpy
  - pandas
  - scikit-learn
  - scipy
  - seaborn
prefix: /home/jovyan/.local/share/envs/final-group08
